### ISSUE TITLE
Sept-2018-Test-Fix

### ISSUE THREAD

**Issue by deltadan** [Microsoft/MCW-Business-continuity-and-disaster-recovery#12]
The Test fix for Sept has been completed and ready for QA.  The Compliance check was run and a document for proof will be emailed to Dawnmarie.
[Compliance - BCDR - September 2018 test-fix.docx](https://github.com/Microsoft/MCW-Business-continuity-and-disaster-recovery/files/2438837/Compliance.-.BCDR.-.September.2018.test-fix.docx)

**Comment by deltadan** [comment]
BTW:  please let me know when you want this to go live as I will have to change some student files etc to make to it work correctly with the changes.

**Comment by DawnmarieDesJardins** [comment]
Hey Dan!  This has been QC'd.  Let me know when you've updated those files and are ready for me to merge.

**Comment by DawnmarieDesJardins** [comment]
Closing issue, test/fix was merged & HTML updated.
