### ISSUE TITLE
SQLVM3 DSC Configuration Link Broken

### ISSUE THREAD

**Issue by oyuksektepeli** [Microsoft/MCW-Business-continuity-and-disaster-recovery#14]
https://github.com/solliancenet/bcdr/blob/sept-2018-test-fix/CustomScripts/SQLVM3Config.zip

This link is broken. And unable to setup resource from template deployment. 

Could you please update.

**Comment by deltadan** [comment]
This bug has been fixed.  Please re-download the scripts and run your deployment again.

**Comment by DawnmarieDesJardins** [comment]
Reviewed and addressed, closing issue.
