### ISSUE TITLE
Configure peering between BCDRIaaSPrimarySite and BCDRIaaSSecondarySite

### ISSUE THREAD

**Issue by korpet1030** [Microsoft/MCW-Business-continuity-and-disaster-recovery#15]
I think that the JSON file should include to setup peering between BCDRIaaSPrimarySite and BCDRIaaSSecondarySite. SQLVM3 didn't join domain because the peering setting was not established.

**Comment by deltadan** [comment]
We will investigate.  The peering should happen during the deployment.

**Comment by deltadan** [comment]
There was a bug found in the student files. This issue has been resolved and the student files have been updated.  A test has been performed.

**Comment by deltadan** [comment]
Another test has confirmed that the bug has been resolved.  A new set of student files is available now.

**Comment by deltadan** [comment]
The files can be found here: https://www.dropbox.com/s/mfy0hx84ljie3rq/StudentFiles.zip?dl=1
