### ISSUE TITLE
Error when simulating failover

### ISSUE THREAD

**Issue by korpet1030** [Microsoft/MCW-Business-continuity-and-disaster-recovery#16]
When I tried to simulate failover of BCDRIaaSPrimarySite, the following error occurred in Runbook.

"The EnableVMProtection property for the parameter Virtualnetwork is no longer supported. Setting this property has no impact. This property will be removed in a future release. Please remove it from your scripts"

Therefore the backend pool addresses of external load balancer were not changed. How can I fix this issue?

**Comment by deltadan** [comment]
We are in the process of testing this lab now and will provide a fix as soon as possible.

**Comment by deltadan** [comment]
This issue will be resolved with a new pull request.
