### ISSUE TITLE
May 2019 Content Update

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-Business-continuity-and-disaster-recovery#23]
Hello,
This workshop is scheduled for a May 2019 update.  Please give your suggested updates for SME review.

Thanks,
Dawnmarie

**Comment by deltadan** [comment]
The following are the recommendations for the BCDR Update:

1. Move the Azure automation from the current version of AzureRM Powershell to AzureAz. This is a natural evolution to keep up with the 

2. Move from Availablity Sets for the VMs to Availability Zones - this is a huge leap in protection for the solution.  This requirement will be surfaced in the scenario by the customer.  Given that their solution is deployed to one region and uses ASR using AZs allowed for an additional level of reliability that is missing from the current version of the solution.

3.  Replace Traffic Manager for the PaaS solution with Frontdoor.  By addition Frontdoor and removing Traffic Manager we add much more capability to the solution for the customer.  TM only routes traffic to the POPs based on DNS - with Frontdoor we have more capabilities such as geo-filtering, SSL offload, and WAF rules at a global scale.

**Comment by DawnmarieDesJardins** [comment]
@deltadan 
Hi Dan, Please move forward with your suggested updates.

**Comment by cesarfong** [comment]
Review the scripts BCDROnPremPrimarySite.json is throwing error

**Comment by DawnmarieDesJardins** [comment]
Closing with May 2019 content update merge

**Comment by deltadan** [comment]
> Review the scripts BCDROnPremPrimarySite.json is throwing error

this was resolved with the last PR.
