### ISSUE TITLE
Failed Template Deployment using BCDROnPremPrimarySite.json

### ISSUE THREAD

**Issue by danangsw** [microsoft/MCW-Business-continuity-and-disaster-recovery#25]
I get deployment failed while deploying template  "BCDROnPremPrimarySite.json", with following details message:

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"VM has reported a failure when processing extension 'HyperVHostConfig'. Error message: \\\"DSC Configuration 'Main' completed with error(s). Following are the first few: PowerShell DSC resource MSFT_ScriptResource failed to execute Set-TargetResource functionality with error message: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. The SendConfigurationApply function did not succeed.\\\".\"\r\n }\r\n ]\r\n }\r\n}"}]}

**Comment by deltadan** [comment]
Thank you for reporting your issue.  I will investigate update this issue based on my findings.  One question: did you get this issue multiple times?

**Comment by danangsw** [comment]
Hi Dan,

Anyway I did it multiple times, here the result of my last attempt:

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"VM has reported a failure when processing extension 'HyperVHostConfig'. Error message: \\\"DSC Configuration 'Main' completed with error(s). Following are the first few: 'OnPremVM' failed to start.\\n\\nNot enough memory in the system to start the virtual machine OnPremVM.\\n\\nCould not initialize memory: Ran out of memory (0x8007000E).\\r\\n\\r\\n'OnPremVM' failed to start. (Virtual machine ID F7841B12-47A7-40BA-893A-9D1010A89C35)\\n\\nNot enough memory in the system to start the virtual machine OnPremVM with ram size 2048 megabytes. (Virtual machine ID F7841B12-47A7-40BA-893A-9D1010A89C35)\\n\\n'OnPremVM' could not initialize memory: Ran out of memory (0x8007000E). (Virtual machine ID F7841B12-47A7-40BA-893A-9D1010A89C35) The PowerShell DSC resource '[Script]ConfigureHyperV' with SourceInfo 'C:\\\\Packages\\\\Plugins\\\\Microsoft.Powershell.DSC\\\\2.77.0.0\\\\DSCWork\\\\HyperVHostConfig.0\\\\HyperVHostConfig.ps1::39::3::Script' threw one or more non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details. The SendConfigurationApply function did not succeed.\\\".\"\r\n }\r\n ]\r\n }\r\n}"}]}

Thanks,

**Comment by deltadan** [comment]
I was unable to repro the orignal error.

I did repro the issue that you just reported in your comment.  Investigating this issue.

**Comment by deltadan** [comment]
I resolved this issue, but changing the size of the VM in the template at deployment.  We will provide a change to the upcoming Pull Request that will be going in this repo in the next few days.  For now, you can change the VM size template to allow for more RAM:

"HyperVHostVmSize": "Standard_D4s_v3",

**Comment by DawnmarieDesJardins** [comment]
Closing with May 2019 update merge.
