### ISSUE TITLE
Update to zone-redundant SQL Databases

### ISSUE THREAD

**Issue by deltadan** [microsoft/MCW-Business-continuity-and-disaster-recovery#26]
Microsoft has just released this capability and should be included in this MCW. https://azure.microsoft.com/en-us/updates/zone-redundant-sql-dbs-and-elastic-pools-are-now-generally-available-in-three-additional-regions/

**Comment by DawnmarieDesJardins** [comment]
Marking issue as an enhancement for the next scheduled update.

**Comment by crpietschmann** [comment]
We'll need to be sure to update the Lab steps with descriptions of what regions support this feature, as it may not be in all regions yet. This is essentially a Checkbox feature to enable, so it wont add much extra to the lab, but will be a great add to the BCDR scenario.

The original announcement blog post (https://azure.microsoft.com/en-us/blog/azure-sql-database-now-offers-zone-redundant-premium-databases-and-elastic-pools/) mentions the regions that were available for this feature at time of release. The currently supported region list will need to be verified when this update is made.

**Comment by crpietschmann** [comment]
This was added in the March 2020 Update branch and issue, so I'm closing this one.
