### ISSUE TITLE
Exercise 1: Task 2 : BCDROnPremPrimarySite Template failing.

### ISSUE THREAD

**Issue by SeeratArora** [microsoft/MCW-Business-continuity-and-disaster-recovery#27]
[Exercise 1: Task 2](https://github.com/microsoft/MCW-Business-continuity-and-disaster-recovery/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Business%20continuity%20and%20disaster%20recovery.md#task-2-deploy-on-premises-environment) BCDROnPremPrimarySite.json template is failing with error message : 

![image](https://user-images.githubusercontent.com/50323628/62453421-eb748880-b78f-11e9-9314-41bdbe355487.png)

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"VM has reported a failure when processing extension 'HyperVHostConfig'. Error message: \\\"DSC Configuration 'Main' completed with error(s). Following are the first few: 'OnPremVM' failed to start.\\n\\nNot enough memory in the system to start the virtual machine OnPremVM.\\n\\nCould not initialize memory: Ran out of memory (0x8007000E).\\r\\n\\r\\n'OnPremVM' failed to start. (Virtual machine ID DDCE84F5-4458-4D22-A5DE-DA0D4D6761FC)\\n\\nNot enough memory in the system to start the virtual machine OnPremVM with ram size 2048 megabytes. (Virtual machine ID DDCE84F5-4458-4D22-A5DE-DA0D4D6761FC)\\n\\n'OnPremVM' could not initialize memory: Ran out of memory (0x8007000E). (Virtual machine ID DDCE84F5-4458-4D22-A5DE-DA0D4D6761FC) The PowerShell DSC resource '[Script]ConfigureHyperV' with SourceInfo 'C:\\\\Packages\\\\Plugins\\\\Microsoft.Powershell.DSC\\\\2.77.0.0\\\\DSCWork\\\\HyperVHostConfig.0\\\\HyperVHostConfig.ps1::39::3::Script' threw one or more non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details. The SendConfigurationApply function did not succeed.\\\".\"\r\n }\r\n ]\r\n }\r\n}"}]}

**Comment by SeeratArora** [comment]
@DawnmarieDesJardins  We have workshop scheduled next week , could you please check on this on priority bases.

**Comment by timahenning** [comment]
Hi Seerat,

I ran through the lab and I was able to get it to work using the Standard D2s v3 (2 vcpus, 8 GiB memory) as defined in the ARM template.  Reviewing your error message, it appears the OnPremVM you are using only has 2gig RAM and there was not enough memory.  

Try running the ARM template and let me know if you are still having issues.

Tim

**Comment by DawnmarieDesJardins** [comment]
@SeeratArora 
Hi Seerat,
Can you please confirm that this has been taken care of and that you're good?
Dawnmarie

**Comment by SeeratArora** [comment]
@DawnmarieDesJardins and @timahenning 

We see that the VM size has been updated to D4s_v3 and it's working as expected, therefore template is working for me.

Thanks

**Comment by akn9050** [comment]
Getting the following issue when deploying the template BCDROnPremPrimarySite.json:
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-debug for usage details.","details":[{"code":"Conflict","message":"{\r\n \"status\": \"Failed\",\r\n \"error\": {\r\n \"code\": \"ResourceDeploymentFailure\",\r\n \"message\": \"The resource operation completed with terminal provisioning state 'Failed'.\",\r\n \"details\": [\r\n {\r\n \"code\": \"VMExtensionProvisioningError\",\r\n \"message\": \"VM has reported a failure when processing extension 'HyperVHostConfig'. Error message: \\\"DSC Configuration 'Main' completed with error(s). Following are the first few: PowerShell DSC resource MSFT_ScriptResource failed to execute Set-TargetResource functionality with error message: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. The SendConfigurationApply function did not succeed.\\\".\"\r\n }\r\n ]\r\n }\r\n}"}]}

I am trying to fix it. Can you also check on this.

**Comment by timahenning** [comment]
Are you using the ARM template?

Tim

**Comment by akn9050** [comment]
Hi Tim, 

It got failed when i deployed the template for the first time. After that i cleaned the all resources from RG and deployed the template again and it worked. Deployment got succeed.

**Comment by DawnmarieDesJardins** [comment]
Closing issue as resolved.
