### ISSUE TITLE
Missing the "Before hands on lab" preparation steps

### ISSUE THREAD

**Issue by DivineOps** [Microsoft/MCW-Business-continuity-and-disaster-recovery#3]
Missing the Before hands on lab part, including the link to the templates that need to be downloaded to go through the HOL

In the Word doc, the steps are under the following titles:

Before the hands-on lab	
Task 1: Create a virtual machine to execute the lab	
Task 2: Download hands-on lab step by step support files to LABVM	
Task 3: Install SQL Server Express on LABVM	
Task 4: Create the resource groups

**Comment by DawnmarieDesJardins** [comment]
Closing this issue.
Previous lab documents included a before the lab section.  In GitHub, the before the lab instruction are their own document titled: Before the lab
