### ISSUE TITLE
Failover scripts reference dropbox?

### ISSUE THREAD

**Issue by larryclaman** [microsoft/MCW-Business-continuity-and-disaster-recovery#31]
The failover script used in exercise 1, task 2, steps 17-18 pulls four failover scripts from a dropbox repository.  Not clear to me why these required scripts are stored in Dropbox rather than directly in this github repo (or at a minimum, in an Azure Storage Account).

Code in question:

```
$ASRFailoverScriptPath = "https://www.dropbox.com/s/q3tb6h2u1qqzqx8/ASRFailOver.ps1?dl=1"
$ASRFailoverScriptPathSQLVM1 = "https://www.dropbox.com/s/t3f2wx9rzlwgkbx/ASRFailOverSQLVM1.ps1?dl=1"
$ASRFailoverScriptPathSQLVM2 = "https://www.dropbox.com/s/cfr2v9alyslct8c/ASRFailOverSQLVM2.ps1?dl=1"
$ASRFailBackScriptPath = "https://www.dropbox.com/s/szq4zkq75xa3ue1/ASRFailBack.ps1?dl=1"
```

I suggest that these scripts be migrated into this repo and managed along with the rest of the code.

**Comment by DawnmarieDesJardins** [comment]
@larryms 
Thanks for the feedback Larry.  It looks like this is something our authors should review in the next refresh cycle.  I'm marking your issue as an enhancement.

**Comment by crpietschmann** [comment]
I did copy some files down from DropBox and put them in this repo with the previous update that was made. This should be completed, but for some reason the Issue wasn't closed. We'll need to just verify this is completed when we do the next update and then close out this Issue.

**Comment by crpietschmann** [comment]
There were a couple .zip files still pulling from Dropbox. I updated the "Update-March-2020" that I'm working in to use Git LFS (Large File System) and committed these .zip files into the GitHub repo and updated scripts accordingly to pull from GitHub.

**Comment by crpietschmann** [comment]
This was added in the March 2020 Update branch and issue, so I'm closing this one.
