### ISSUE TITLE
Enhancement:  On-prem to Azure exercise should failover, not migrate

### ISSUE THREAD

**Issue by larryclaman** [microsoft/MCW-Business-continuity-and-disaster-recovery#32]
This workshop is about Business continuity and disaster recovery.  The on-prem scenario, however, **migrates** the on-prem VM to Azure, rather than failing it over and then failing back (like the other exercises.)

As this is a valid use case for many customers, I think the workshop should be refactored to cover failover & failback scenario, rather than migration,

**Comment by crpietschmann** [comment]
Given that this is a BCDR MCW, it does make sense for the Lab scenario to be a Failover, instead of a Migration. We'll have to assess this scope and invasiveness of this change when we perform the next update to the MCW, and definitely include this change if makes sense.

**Comment by crpietschmann** [comment]
This was added in the March 2020 Update branch and issue, so I'm closing this one.
