### ISSUE TITLE
Enhancement: On-prem application should incorporate a database driven web app

### ISSUE THREAD

**Issue by larryclaman** [microsoft/MCW-Business-continuity-and-disaster-recovery#33]
The on-prem to azure example uses a simple php app that displays a simple web page.  There does not appear to be any database involved or any 'state' that changes.

I suggest that for the on-prem to Azure example to be useful, it should use an application that relies on a back-end database (eg shopping cart app or something similar).

**Comment by DawnmarieDesJardins** [comment]
Labeling as an enhancement for next update

**Comment by crpietschmann** [comment]
The point of the PHP app in the Lab was to include a non-Windows workload in the BCDR scenario. To do this the Lab will need to be modified to have a database server deployed for the PHP app and the app modified to be database-driven in some fashion. We'll need to look at the overall scope of the Lab and make sure this doesn't add too much complexity to it. This is a really long lab to do as it stands, and we don't really want to add much more steps/time to it if we can help it.

**Comment by crpietschmann** [comment]
While this enhancement would be nice, the priority isn't very high. It didn't make it into this update round, as there were higher priority updates to get completed. Leaving this Issue open so this is tracked for a future update cycle.
