### ISSUE TITLE
Cannot deploy PaaS environment

### ISSUE THREAD

**Issue by patrbng** [microsoft/MCW-Business-continuity-and-disaster-recovery#35]
When I try to deploy the PaaS environment, it fails with "-Location 'East US 2' is not accepting creation of new Windows Azure SQL Database servers at this time."   I've tried it in several other regions with the same error.  I've also tried it using my Pay-As-You-Go subscription on a different tenant in case it was an issue with my MSDN subscription.

**Comment by deltadan** [comment]
This seems to be an Azure capacity issue for your subscription type.  I would try to deploy to North and East Europe and see if you have better luck.  The regions you choose should support Availablity Zones. https://azure.microsoft.com/en-us/global-infrastructure/regions/

**Comment by patrbng** [comment]
Thanks.  That worked.

**Comment by deltadan** [comment]
Due to the popularity of Availablity Zones in East US 2 and Central US some subscriptions aren't able to create these types of workloads for non-production uses.  Using North and West Europe will allow you to complete the MCW without an issue as of the date of this issue.  Thanks!  Glad it worked!
