### ISSUE TITLE
Error creating BCDRIaaSPrimarySite (Core Quota Limit)

### ISSUE THREAD

**Issue by XtremeDR** [microsoft/MCW-Business-continuity-and-disaster-recovery#36]
When attempting to create the BCDRIaaSPrimarySite deployment the following error is displayed:

**This operation couldn't be completed as it results in exceeding quota limit of Core.  Maximum allowed: 10, Current in use: 4, Additional requested: 10.**

Note: This particular version appeared when I attempted to re-try this deployment after it failed the first time with a similar error, the 4 cores present are from other deployments in this lab series.  

I am using an Azure Pass for this lab, it appears that the number of cores that they will allow is limited to 10, though much of the documentation for this says it should be a limit of 20.  Has the quota limit on this resource changed recently or am I doing something wrong?

**Comment by DawnmarieDesJardins** [comment]
@timahenning
Collaborator invite sent, please accept.  Please review/advise on issue.
Thanks!

**Comment by deltadan** [comment]
I'm sorry, but Azure passes typically don't allow for enough cores in a given region to complete this lab.  You will have to use a different type of subscription in order to complete this MCW. From the error message, it does appear that you are using some of the cores.  If you were to free up the cores you might be able to continue.

**Comment by XtremeDR** [comment]
The information that Azure Passes don't really work for this course is exactly what I was looking for.  Thank you very much for your time, you can consider this closed.

**Comment by DawnmarieDesJardins** [comment]
Thanks all!
