### ISSUE TITLE
Exercise 1: Task 1: SQLVM1 and SQLVM3 deployed from BCDRIaaSPrimarySite.json file do not have RDP port allowed.

### ISSUE THREAD

**Issue by SeeratArora** [microsoft/MCW-Business-continuity-and-disaster-recovery#37]
As per the lab guide. in [Exercise 1: Task 1](https://github.com/microsoft/MCW-Business-continuity-and-disaster-recovery/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Business%20continuity%20and%20disaster%20recovery.md#task-1-deploy-azure-iaas)
, we are deploying BCDRIaaSPrimarySite.json file. This file will deploy resources out of which there are 2 Virtual Machines named- SQLVM1 and SQLVM3.

In [Exercise 3: Task 2:](https://github.com/microsoft/MCW-Business-continuity-and-disaster-recovery/blob/master/Hands-on%20lab/HOL%20step-by%20step%20-%20Business%20continuity%20and%20disaster%20recovery.md#task-2-configure-iaas-sql-always-on-availability-groups-for-region-to-region-failover) Step 10, we are asked to RDP into both the VMs but RDP Port (3389) is not allowed in them as shown in the image below. 

![image](https://user-images.githubusercontent.com/50323628/69227788-72ffcf00-0ba8-11ea-8e61-e2d4b321a848.png)

Can you please review this as soon as possible.

Thanks,
Seerat

**Comment by timahenning** [comment]
Thank you for reporting this issue.  Please take a moment to review the help and support guidance.  https://microsoftcloudworkshop.com/  We will review your issue soon.

Tim

**Comment by crpietschmann** [comment]
As per Exercise 3: Task 2: Step 10 says `Once in the RDP session to BCDRDC1, select Start and then Remote Desktop. You will need to connect to SQLVM1 for the next steps.` It is asking you to RDP to the BCDRDC1 VM first, then from within that session you are to RDP into the SQLVM1 virtual machine.

The BCDRDC1 VM is used as a Jump Box to connect via RDP and used to gain access to other VMs within the VNET. This is a standard security practice that greatly limits the attack surface area of the VNet.

If you have feedback on how to make the instructions more clear, please let me know.

**Comment by nageshars** [comment]
hi,

unable to get BCDRIaaSPrimarySite.json file to upload in ARM

**Comment by woodyp** [comment]
> hi,
> 
> unable to get BCDRIaaSPrimarySite.json file to upload in ARM

I am sorry for any issues can you describe with a little more detail what the issues is?
