### ISSUE TITLE
January 2020 - content update

### ISSUE THREAD

**Issue by DawnmarieDesJardins** [microsoft/MCW-Business-continuity-and-disaster-recovery#38]
This workshop is scheduled for a January 2020 content update. Please review open issues #26 #30 #31 #32 #33 and provide additional recommended changes for SME review.

**Comment by crpietschmann** [comment]
I added some notes and comments to the Issues listed. Some of these changes make sense, and others we'll have to assess when we dig in to perform the update. This is a really long lab as-is, and we don't want to add too much more complexity and time to it if we can help it. Perhaps we could simplify it some too, but that will need to be assessed when we run through the update.

**Comment by DawnmarieDesJardins** [comment]
January update postponed, closing issue.
