### ISSUE TITLE
Exercise 1 Task 1

### ISSUE THREAD

**Issue by himanshuahlawat31** [microsoft/MCW-Business-continuity-and-disaster-recovery#39]
In Exercise 1 task 1 , while deploying BCDRIAAS template it is getting failed , when i checked in logs it was throwing error as **System.OutOfMemoryException** it's due to low memory so when i change size of sqlvms from standard f2s to  to standard D2s_v3 it worked

**Comment by timahenning** [comment]
@himanshuahlawat31 The Before Hands on Lab requests you use a D4_v3 set up for the VM which has more memory and CPU than D2s_v3.  Did you use that configuration first?

![image](https://user-images.githubusercontent.com/48766586/70811824-43914c00-1d7b-11ea-9adf-0ccf2bfc7461.png)

**Comment by timahenning** [comment]
Closing this issue for now.  Please let me know if you have additional questions.
