### ISSUE TITLE
Update March 2020

### ISSUE THREAD

**Issue by crpietschmann** [microsoft/MCW-Business-continuity-and-disaster-recovery#40]
These are the changes made for the March 2020 Update to this MCW using the `Update-March-2020` branch:

- Move "OnPremLinuxVM.zip" file into the Github repo; in order to do this [Git LFS (Large File System) needed to be enabled on the GitHub repo](https://help.github.com/en/github/managing-large-files/configuring-git-large-file-storage). Related to Issue #31
- Update the Azure SQL Database created for the PaaS environment to use Zone Redundant pricing tier for higher availability. Related to Issue #26
- Changed the wording and UI screenshots for specifying a Failover with ASR rather than a Migrate. Related to Issue #32
- Updated a couple VM sizes to be larger, to reduce script extension timeout errors when deploying templates. Affected ARM Templates: `BCDRIaaSPrimarySite.json`, `BCDRIaaSSecondarySite.json`

_FYI, Issue #30 to Upgrade to VS'2019 was actually done previously, so I closed out that issue._

**Comment by crpietschmann** [comment]
PR #41 was submitted with the code/file changes for this update cycle for the MCW.

**Comment by DawnmarieDesJardins** [comment]
Closing issue with merge of PR #41
