### ISSUE TITLE
IIS Website Not Running?

### ISSUE THREAD

**Issue by liamfoneill** [microsoft/MCW-Business-continuity-and-disaster-recovery#42]
I got as far as task 68 (of "Task 2: Configure IaaS SQL Always On availability groups for region to region failover") and got stuck. Rather than seeing the Contoso Insurance website when I browse to the DNS name of the Azure Load Balancer Public IP, I got the default IIS page. I checked both WebVMs manually and both display this default page. I RDP to both Web VMs (1 and 2) and only see the default site running:

![image](https://user-images.githubusercontent.com/1243172/76777248-d2a96800-679f-11ea-9cee-797fe855778c.png)

**Comment by crpietschmann** [comment]
@liamfoneill Could you check the resource group and make sure there aren't any failed deployments? It's possible the script extensions timed out when deploying to the VM.

**Comment by liamfoneill** [comment]
I think you are right. I only see the domain join script.
________________________________

**Comment by crpietschmann** [comment]
Unfortunately, when this happens during the deployment of the template, you need to delete the resource group and re-run the deployment. Azure doesn't re-run script extensions when you re-deploy a ARM Template a second time. Also, there is no repeatable reason the script timeouts occur, they appear to be random when you deploy the ARM Template. This seems to be just how ARM does script extensions...

**Comment by ahmedsza** [comment]
Same issue here. The problem seems to be that the powershell script has this line - $zipDownload = "https://github.com/microsoft/MCW-Business-continuity-and-disaster-recovery/raw/Update-March-2020/Hands-on%20lab/NestedDeployments/CustomScripts/ContosoInsuranceIIS.zip"

and this location does not exist

**Comment by ahmedsza** [comment]
A temp fix - copy the zip from https://github.com/microsoft/MCW-Business-continuity-and-disaster-recovery/blob/master/Hands-on%20lab/NestedDeployments/CustomScripts/ContosoInsuranceIIS.zip into webvm1 and webvm2, then extract it - and then copy it to inetpub/wwwroot

**Comment by crpietschmann** [comment]
@ahmedsza Thanks for posting the fix you found! Some how this URL got messed up in the scripts, I've fixed it and committed those changed to `master`.
