### ISSUE TITLE
June 2020 Update Suggestions

### ISSUE THREAD

**Issue by timahenning** [microsoft/MCW-Business-continuity-and-disaster-recovery#44]

**Comment by crpietschmann** [comment]
Here are my suggested updates to make to the BCDR MCW:

1. Update the OnPremVM to Azure migration to use Azure Migrate service
2. Increase automation of the lab setup steps to reduce the overall time needed to create necessary resource groups and deploy ARM Templates. This is a long lab and reducing setup time will help focus time on core parts of the lab exercise. 
3. Add Azure CLI script that can be used from Azure Cloud Shell to more easily Delete all BCDR resource groups for cleaning up the lab
4. Update screenshots for recent Azure portal changes

**Comment by DawnmarieDesJardins** [comment]
The June 2020 update has been changed to a June test/fix.  Closing the update issue.
Thanks Chris!
