### ISSUE TITLE
Template Deployment Errors

### ISSUE THREAD

**Issue by cankarahaliloglu** [microsoft/MCW-Business-continuity-and-disaster-recovery#45]
HOL\Demployments\* templates cannot validated

Deployment validation failed.
Additional details from the underlying API that might be helpful: The template deployment 'Microsoft.Template' is not valid according to the validation procedure.

**Comment by crpietschmann** [comment]
I just tested the deployment templates for this lab again, and they all passed validation without issue. How did you import the ARM Templates? Did you upload the files, or did you copy/paste the file contents? It's possible if you copy/pasted that the file was messed up some how.
Please try again, and everything should work as expected.

**Comment by timahenning** [comment]
@cankarahaliloglu Are you still having problems?

Tim

**Comment by himanshuahlawat31** [comment]
HOL\Demployments* templates cannot validated

Deployment validation failed.
Additional details from the underlying API that might be helpful: The template deployment 'Microsoft.Template' is not valid according to the validation procedure.

I am also facing this issue while deploying Iaas template

**Comment by DawnmarieDesJardins** [comment]
@crpietschmann 
Hi Chris.  Please review & advise.

**Comment by timahenning** [comment]
@himanshuahlawat31 @cankarahaliloglu Chris had posted a few questions.  Can you help us out with a few debugging steps?

Thanks,

Tim

**Comment by himanshuahlawat31** [comment]
Hi @timahenning , when we tried the deployment previously it was getting failed due to azure deployment issue .
After that we tried deploying the templates and we didn't faced any failure in IAAS template

**Comment by deltadan** [comment]
@himanshuahlawat31 we don't have enough information to start to troubleshoot the issue.  Can you please confirm the template filename which is not deploying and copy the error text into the response?   Also, please confirm that you are doing the deployment after completing the steps using the instructions here: https://github.com/microsoft/MCW-Business-continuity-and-disaster-recovery/blob/master/Hands-on%20lab/Before%20the%20HOL%20-%20Business%20continuity%20and%20disaster%20recovery.md

**Comment by DawnmarieDesJardins** [comment]
Closing issue due to no response.  Please reopen if needed.
