### ISSUE TITLE
Iaas template failing 

### ISSUE THREAD

**Issue by himanshuahlawat31** [microsoft/MCW-Business-continuity-and-disaster-recovery#46]
while deploying iaas template we are facing issue it is throwing error as:
Deployment validation failed.
Additional details from the underlying API that might be helpful: The template deployment 'Microsoft.Template' is not valid according to the validation procedure.

**Comment by crpietschmann** [comment]
Do you have any more information about the error message being displayed? I have personally tested the templates recently and they are all working as expected.

**Comment by himanshuahlawat31** [comment]
It turned out to be issue from Azure , we tried deploying template and it got succeeded
