### ISSUE TITLE
Reference to script not resolving

### ISSUE THREAD

**Issue by jonsatchwell** [microsoft/MCW-Business-continuity-and-disaster-recovery#49]
The Runbook for SQL failover is pointing to a script that doesn't resolve. Is this referencing a branch that has now been merged?

Run book imported and published in to Azure Automation
ASRRunBookSQL.ps1

e.g. from line 32
$ASRFailoverScriptPathSQLVM1 = "https://raw.githubusercontent.com/Microsoft/MCW-Business-continuity-and-disaster-recovery/Update-March-2020/Hands-on%20lab/StudentFiles/Deployments/ASRFailOverSQLVM1.ps1"

**Comment by woodyp** [comment]
Pleas us master I will remove the update branch soon.
