### ISSUE TITLE
cannot log on to linux vm in hyper v

### ISSUE THREAD

**Issue by jonsatchwell** [microsoft/MCW-Business-continuity-and-disaster-recovery#50]
I tried running the hyper v steps for the on prem to azrue ASR but the log in provided didn't work in the terminal from the hyperv VM.  The account I am referring to is the mcwadmin account with the demo@pass123 password as instructed - I tested writing this out on the VM to make sure that any special characters were being written as expected - often keyboard or regional settings can afftec this between machines. 

Is there somewhere in the template I can check this or edit/set it before the I do the deployment?

**Comment by woodyp** [comment]
@jonsatchwell all user names and passwords are in the various json files and all are set the the correct values. Have you trysted to setup the environment again? Are you getting any error messages when you are stetting up the OpPrim site?

**Comment by jonsatchwell** [comment]
Sorry woodyp.  I see this is closed. I have removed the environment and will set it up again.  I couldn't find username and password setting specifically for the hyper v machine for the on-prem site, may be it is automatically propogated from the Azure vm login in to the hyper v linux machine.  I can try and deploy again and see if it works

**Comment by woodyp** [comment]
Please let me know how it goes happy to help

**Comment by deltadan** [comment]
the username and password for the VM inside of hyperv is not set by the json files, but it should match the documentation as it hasn't been changed in over a year.
