### ISSUE TITLE
Deployment failed - DNS record bcdrdc8675309.eastus2.cloudapp.azure.com is already used by another public IP

### ISSUE THREAD

**Issue by nageshars** [microsoft/MCW-Business-continuity-and-disaster-recovery#52]
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"code\": \"DnsRecordInUse\",\r\n \"message\": \"DNS record bcdrdc8675309.eastus2.cloudapp.azure.com is already used by another public IP.\",\r\n \"details\": []\r\n }\r\n}"},{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"code\": \"InUseSubnetCannotBeDeleted\",\r\n \"message\": \"Subnet DATA is in use by /subscriptions/ed570a34-a090-4e9b-934b-1d201de1f7c4/resourceGroups/BCDRIaaSPrimarySite/providers/Microsoft.Network/loadBalancers/SQLAOGILB/frontendIPConfigurations/LoadBalancerFrontend and cannot be deleted. In order to delete the subnet, delete all the resources within the subnet. See aka.ms/deletesubnet.\",\r\n \"details\": []\r\n }\r\n}"}]}

**Comment by woodyp** [comment]
As is stated in the instructions "The name will need to be lowercase and 3-24 characters consisting of letters & numbers and be unique to all of Azure. In the example, the DNS name bcdrdc8675309 was used." so you used a preexisting dns name. Please use a different. You will need to not what you used for later steps.

**Comment by nageshars** [comment]
> As is stated in the instructions "The name will need to be lowercase and 3-24 characters consisting of letters & numbers and be unique to all of Azure. In the example, the DNS name bcdrdc8675309 was used." so you used a preexisting dns name. Please use a different. You will need to not what you used for later steps.

Thanks worked...have encountered 1 more
