### ISSUE TITLE
DeploymentFailed","message":"At least one resource deployment operation failed

### ISSUE THREAD

**Issue by nageshars** [microsoft/MCW-Business-continuity-and-disaster-recovery#53]
{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/DeployOperations for usage details.","details":[{"code":"BadRequest","message":"{\r\n \"error\": {\r\n \"code\": \"InUseSubnetCannotBeDeleted\",\r\n \"message\": \"Subnet DATA is in use by /subscriptions/ed570a34-a090-4e9b-934b-1d201de1f7c4/resourceGroups/BCDRIaaSPrimarySite/providers/Microsoft.Network/loadBalancers/SQLAOGILB/frontendIPConfigurations/LoadBalancerFrontend and cannot be deleted. In order to delete the subnet, delete all the resources within the subnet. See aka.ms/deletesubnet.\",\r\n \"details\": []\r\n }\r\n}"}]}

**Comment by woodyp** [comment]
This happens when the steps don't work through the first time. You will need to delete all resource groups and start the deployment again.
