### ISSUE TITLE
Azure Site Recovery UI and instructions change

### ISSUE THREAD

**Issue by anushabc** [microsoft/MCW-Business-continuity-and-disaster-recovery#54]
In exercise 3, Azure Site Recovery instruction and screenshots needs to be updated. And in exercise3 task2 configure cloud witness failed with the error "The TLS version of the connection is not permitted on this storage account".

**Comment by DawnmarieDesJardins** [comment]
@anushabc 
Hello.  Thanks for reaching out.  Unfortunately, this workshop is scheduled to be retired effective 11/30/20 so we will not be updating the content before that.
